#!/bin/sh

# This script runs pianobooster with fluidsynth
# It supports JACK and ALSA both
# It switches on JACK automatically if ALSA is not available
# License: same with Pianobooster
# Author: Alexey Loginov <alexl@mageia.org>

use_jack="0"

MES1="Error: SoundFonts FluidR3_GM.sf2 and FluidR3_GS.sf2 were not found!"
MES2="Error: fluidsynth was not run!"
MES3="Error: SoundFont FluidR3_GM.sf2 was not found!"
MES4="Error: SoundFont FluidR3_GS.sf2 was not found!"
MES5="Please try again!"
MES6="Error: fluidsynth was not found or broken!"
MES7="Error: jackd was not found!"
MES8="Starting fluidsynth..."
MES9="Please wait 10 more seconds!"
MES10="Fluidsynth does not have ALSA support!"
MES11="Switching on using JACK..."

lang=`echo $LANGUAGE|cut -d ":" -f 2`

if [ -z "$lang" ]
then
  lang=`echo $LANG|cut -d "_" -f 1`
fi

case $lang in
     ru|be)
          MES1="Ошибка: Звуковые шрифты FluidR3_GM.sf2 и FluidR3_GS.sf2 не были найдены!"
          MES2="Ошибка: fluidsynth не был запущен!"
          MES3="Ошибка: Звуковой шрифт FluidR3_GM.sf2 не был найден!"
          MES4="Ошибка: Звуковой шрифт FluidR3_GS.sf2 не был найден!"
          MES5="Пожалуйста, попытайтесь снова!"
          MES6="Ошибка: fluidsynth не был найден, или он неработоспособен!"
          MES7="Ошибка: jackd не был найден!"
          MES8="Запускается fluidsynth..."
          MES9="Пожалуйста, ожидайте около 10 секунд!"
          MES10="Fluidsynth не имеет поддержки ALSA!"
          MES11="Переключение на использование JACK..."
          ;;
     fi)
          MES1="Virhe: FluidR3_GM.sf2 ja FluidR3_GS.sf2 ei löytynyt!"
          MES2="Virhe: fluidsynth ei toimi!"
          MES3="Virhe: FluidR3_GM.sf2 ei löytynyt!"
          MES4="Virhe: FluidR3_GS.sf2 ei löytynyt!"
          MES5="Yritä uudelleen!"
          MES6="Virhe: fluidsynth ei löytynyt tai rikki!"
          MES7="Virhe: jakkia ei löytynyt!"
          MES8="Alkaa fluidsynth..."
          MES9="Odota 10 sekuntia!"
          MES10="Fluidsynthillä ei ole ALSA-tukea!"
          MES11="Kytketään käyttäen JAKKI..."
          ;;
     de)
          MES1="Fehler: SoundFonts FluidR3_GM.sf2 und FluidR3_GS.sf2 wurden nicht gefunden!"
          MES2="Fehler: Fluidsynth wurde nicht ausgeführt!"
          MES3="Fehler: SoundFont FluidR3_GM.sf2 wurde nicht gefunden!"
          MES4="Fehler: SoundFont FluidR3_GS.sf2 wurde nicht gefunden!"
          MES5="Bitte erneut versuchen!"
          MES6="Fehler: Fluidsynth wurde nicht gefunden oder ist beschädigt!"
          MES7="Fehler: jackd wurde nicht gefunden!"
          MES8="Fluidsynth wird gestartet..."
          MES9="Bitte noch 10 Sekunden warten!"
          ;;
     uk)
          MES1="Помилка: не знайдено звукових шрифтів FluidR3_GM.sf2 та FluidR3_GS.sf2!"
          MES2="Помилка: fluidsynth не запущено!"
          MES3="Помилка: не знайдено звукового шрифту FluidR3_GM.sf2!"
          MES4="Помилка: не знайдено звукового шрифту FluidR3_GS.sf2!"
          MES5="Будь ласка, повторіть спробу!"
          MES6="Помилка: fluidsynth не знайдено або дані програми пошкоджено!"
          MES7="Помилка: jackd не знайдено!"
          MES8="Запускаємо fluidsynth..."
          MES9="Будь ласка, зачекайте ще 10 секунд!"
          MES10="У Fluidsynth не передбачено підтримки ALSA!"
          MES11="Перемикаємося на використання JACK..."
          ;;
     cs)
          MES1="Chyba: Zvukové banky FluidR3_GM.sf2 a FluidR3_GS.sf2 nebyly nalezeny!"
          MES2="Chyba: fluidsynth nebyl spuštěn!"
          MES3="Chyba: Zvuková banka FluidR3_GM.sf2 nebyla nalezena!"
          MES4="Chyba: Zvuková banka FluidR3_GS.sf2 nebyla nalezena!"
          MES5="Zkuste to, prosím, znovu!"
          ;;
     gl)
          MES1="Erro: Non se atopou  SoundFonts FluidR3_GM.sf2 e FluidR3_GS.sf2!"
          MES2="Erro: o fluidsynth non foi executado!"
          MES3="Erro: Non se atopou SoundFont FluidR3_GM.sf2!"
          MES4="Erro: Non se atopou SoundFont FluidR3_GS.sf2!"
          MES5="Tenteo de novo!"
          ;;
     bg)
          MES1="Грешка: SoundFonts FluidR3_GM.sf2 and FluidR3_GS.sf2 не бяха намерени!"
          MES2="Грешка: Не намирам fluidsynth!"
          MES5="Моля, опитайте отново!"
          ;;
     pl)
          MES1="Błąd: SoundFonts FluidR3_GM.sf2 i FluidR3_GS.sf2 nie zostały znalezione!"
          MES2="Błąd: fluidsynth nie został uruchomiony!"
          MES3="Błąd: Nie znaleziono SoundFont FluidR3_GM.sf2!"
          MES4="Błąd: Nie znaleziono SoundFont FluidR3_GS.sf2!"
          MES5="Spróbuj ponownie!"
          MES6="Błąd: fluidsynth nie został znaleziony lub jest uszkodzony!"
          MES7="Błąd: jackd nie został znaleziony!"
          MES9="Poczekaj jeszcze 10 sekund!"
          MES10="Fluidsynth nie ma wsparcia ALSA!"
          ;;
esac

if [ -f "/usr/share/soundfonts/FluidR3_GM.sf2" ]
then
  sf2_1="/usr/share/soundfonts/FluidR3_GM.sf2"
fi

if [ -f "/usr/share/soundfonts/FluidR3_GS.sf2" ]
then
  sf2_2="/usr/share/soundfonts/FluidR3_GS.sf2"
fi

if [ -f "/usr/share/sounds/sf2/FluidR3_GM.sf2" ]
then
  sf2_1="/usr/share/sounds/sf2/FluidR3_GM.sf2"
fi

if [ -f "/usr/share/sounds/sf2/FluidR3_GS.sf2" ]
then
  sf2_2="/usr/share/sounds/sf2/FluidR3_GS.sf2"
fi

if [ -f "/usr/local/share/sounds/sf2/FluidR3_GM.sf2" ]
then
  sf2_1="/usr/local/share/sounds/sf2/FluidR3_GM.sf2"
fi

if [ -f "/usr/local/share/sounds/sf2/FluidR3_GS.sf2" ]
then
  sf2_2="/usr/local/share/sounds/sf2/FluidR3_GS.sf2"
fi

notify_send=`notify-send -v 2>/dev/null`

fluidsynth=`fluidsynth -V 2>/dev/null`

if [ -z "$fluidsynth" ]
then
  echo "$MES6"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES6"
  fi
  exit 1
fi

if [ -z "$sf2_1" ] && [ -z "$sf2_2" ]
then
  echo "$MES1"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES1"
  fi
  exit 1
fi

if [ -z "$sf2_1" ]
then
  echo "$MES3"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES3"
  fi
  exit 1
fi

if [ -z "$sf2_2" ]
then
  echo "$MES4"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES4"
  fi
  exit 1
fi

alsa=`fluidsynth -o help|grep alsa`

if [ "$use_jack" = "0" ] && [ -z "$alsa" ]
then
  echo "$MES10" "$MES11"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES10 $MES11"
  fi
  use_jack="1"
fi

if [ ! -f "/usr/bin/jackd" ] && [ "$use_jack" = "1" ]
then
  if [ ! -f "/usr/local/bin/jackd" ]
  then
    echo "$MES7"
    if [ ! -z "$notify_send" ]
    then
      notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES7"
    fi
    exit 1
  fi
fi

if [ "$use_jack" = "1" ]
then
  echo "$MES8" "$MES9"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES8 $MES9"
  fi
fi

if [ "$use_jack" = "1" ]
then
  if [ ! -z "$alsa" ]
  then
    fluidsynth -i -s -g 1 -C 0 -R 0 -r 22050 -c 6 -z 128 -l -a jack -o midi.alsa_seq.id=fs -j $sf2_1 $sf2_2 &
  else
    fluidsynth -i -s -g 1 -C 0 -R 0 -r 22050 -c 6 -z 128 -l -a jack -j $sf2_1 $sf2_2 &
  fi
else
  fluidsynth -i -s -g 1 -C 0 -R 0 -r 22050 -c 6 -z 128 -l -a alsa -o audio.alsa.device=plughw:0 -o midi.alsa_seq.id=fs $sf2_1 $sf2_2 &
fi

PID=$!

if [ "$use_jack" = "1" ]
then
  sleep 10
else
  sleep 3
fi

process=`ps -p $PID -o comm= 2>/dev/null`

if [ -z $process ]
then
  echo "$MES2 $MES5"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES2 $MES5"
  fi
  exit 1
fi

pianobooster

kill $PID

if [ "$use_jack" = "1" ]
then
  sleep 5
fi
