#!/bin/sh

#use_jack="1"

MES1="Error: SoundFonts FluidR3_GM.sf2 and FluidR3_GS.sf2 were not found!"
MES2="Error: fluidsynth was not run!"
MES3="Error: SoundFont FluidR3_GM.sf2 was not found!"
MES4="Error: SoundFont FluidR3_GS.sf2 was not found!"
MES5="Please try again!"
MES6="Error: fluidsynth was not found!"
MES7="Error: /usr/bin/jackd was not found!"
MES8="Starting fluidsynth..."
MES9="Please wait 10 more seconds!"

lang=`echo $LANGUAGE|cut -d ":" --fields=2`

case $lang in
     ru|be)
          MES1="Ошибка: Звуковые шрифты FluidR3_GM.sf2 и FluidR3_GS.sf2 не были найдены!"
          MES2="Ошибка: fluidsynth не был запущен!"
          MES3="Ошибка: Звуковой шрифт FluidR3_GM.sf2 не был найден!"
          MES4="Ошибка: Звуковой шрифт FluidR3_GS.sf2 не был найден!"
          MES5="Пожалуйста, попытайтесь снова!"
          MES6="Ошибка: fluidsynth не был найден!"
          MES7="Ошибка: /usr/bin/jackd не был найден!"
          MES8="Запускается fluidsynth..."
          MES9="Пожалуйста, ожидайте около 10 секунд!"
          ;;
     uk)
          MES1="Помилка: не знайдено звукових шрифтів FluidR3_GM.sf2 та FluidR3_GS.sf2!"
          MES2="Помилка: fluidsynth не запущено!"
          MES3="Помилка: не знайдено звукового шрифту FluidR3_GM.sf2!"
          MES4="Помилка: не знайдено звукового шрифту FluidR3_GS.sf2!"
          MES5="Будь ласка, повторіть спробу!"
          ;;
     cs)
          MES1="Chyba: Zvukové banky FluidR3_GM.sf2 a FluidR3_GS.sf2 nebyly nalezeny!"
          MES2="Chyba: fluidsynth nebyl spuštěn!"
          MES3="Chyba: Zvuková banka FluidR3_GM.sf2 nebyla nalezena!"
          MES4="Chyba: Zvuková banka FluidR3_GS.sf2 nebyla nalezena!"
          MES5="Zkuste to, prosím, znovu!"
          ;;
     gl)
          MES1="Erro: Non se atopou  SoundFonts FluidR3_GM.sf2 e FluidR3_GS.sf2!"
          MES2="Erro: o fluidsynth non foi executado!"
          MES3="Erro: Non se atopou SoundFont FluidR3_GM.sf2!"
          MES4="Erro: Non se atopou SoundFont FluidR3_GS.sf2!"
          MES5="Tenteo de novo!"
          ;;
     bg)
          MES1="Грешка: SoundFonts FluidR3_GM.sf2 and FluidR3_GS.sf2 не бяха намерени!"
          MES2="Грешка: Не намирам fluidsynth!"
          MES5="Моля, опитайте отново!"
          ;;
     pl)
          MES5="Spróbuj ponownie!"
          ;;
esac

if [ -f "/usr/share/soundfonts/FluidR3_GM.sf2" ]
then
  sf2_1="/usr/share/soundfonts/FluidR3_GM.sf2"
fi

if [ -f "/usr/share/soundfonts/FluidR3_GS.sf2" ]
then
  sf2_2="/usr/share/soundfonts/FluidR3_GS.sf2"
fi

if [ -f "/usr/share/sounds/sf2/FluidR3_GM.sf2" ]
then
  sf2_1="/usr/share/sounds/sf2/FluidR3_GM.sf2"
fi

if [ -f "/usr/share/sounds/sf2/FluidR3_GS.sf2" ]
then
  sf2_2="/usr/share/sounds/sf2/FluidR3_GS.sf2"
fi

notify_send=`notify-send -v 2>/dev/null`

fluidsynth=`fluidsynth -V 2>/dev/null`

if [ -z "$fluidsynth" ]
then
  echo "$MES6"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES6"
  fi
  exit 1
fi

if [ ! -f "/usr/bin/jackd" ] && [ ! -z "$use_jack" ]
then
  echo "$MES7"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES7"
  fi
  exit 1
fi

if [ -z "$sf2_1" ] && [ -z "$sf2_2" ]
then
  echo "$MES1"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES1"
  fi
  exit 1
fi

if [ -z "$sf2_1" ]
then
  echo "$MES3"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES3"
  fi
  exit 1
fi

if [ -z "$sf2_2" ]
then
  echo "$MES4"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES4"
  fi
  exit 1
fi

if [ ! -z "$use_jack" ]
then
  echo "$MES8" "$MES9"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES8 $MES9"
  fi
fi

if [ ! -z "$use_jack" ]
then
  fluidsynth -i -s -g 1 -C 0 -R 0 -r 22050 -c 6 -z 128 -l -a jack -j -o midi.alsa_seq.id=fs $sf2_1 $sf2_2 &
else
  fluidsynth -i -s -g 1 -C 0 -R 0 -r 22050 -c 6 -z 128 -l -a alsa -o audio.alsa.device=plughw:0 -o midi.alsa_seq.id=fs $sf2_1 $sf2_2 &
fi

PID=$!

if [ ! -z "$use_jack" ]
then
  sleep 10
else
  sleep 3
fi

process=`ps -p $PID -o comm=`

if [ -z $process ]
then
  echo "$MES2 $MES5"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES2 $MES5"
  fi
  exit 1
fi

pianobooster

kill $PID

if [ ! -z "$use_jack" ]
then
  sleep 5
fi
