#!/bin/sh

lang=`echo $LANGUAGE|cut -d ":" --fields=2`

MES1="Error: SoundFonts FluidR3_GM.sf2 and FluidR3_GS.sf2 were not found!"
MES2="Error: fluidsynth was not run!"
MES3="Error: SoundFont FluidR3_GM.sf2 was not found!"
MES4="Error: SoundFont FluidR3_GS.sf2 was not found!"
MES5="Please try again!"

if [ "$lang" = "ru" ]
then
  MES1="Ошибка: Звуковые шрифты FluidR3_GM.sf2 и FluidR3_GS.sf2 не были найдены!"
  MES2="Ошибка: fluidsynth не был запущен!"
  MES3="Ошибка: Звуковой шрифт FluidR3_GM.sf2 не был найден!"
  MES4="Ошибка: Звуковой шрифт FluidR3_GS.sf2 не был найден!"
  MES5="Пожалуйста, попытайтесь снова!"
fi

if [ -f "/usr/share/soundfonts/FluidR3_GM.sf2" ] && [ -f "/usr/share/soundfonts/FluidR3_GS.sf2" ]
then
  sf2_1="/usr/share/soundfonts/FluidR3_GM.sf2"
  sf2_2="/usr/share/soundfonts/FluidR3_GS.sf2"
fi

if [ -f "/usr/share/sounds/sf2/FluidR3_GM.sf2" ] && [ -f "/usr/share/sounds/sf2/FluidR3_GS.sf2" ]
then
  sf2_1="/usr/share/sounds/sf2/FluidR3_GM.sf2"
  sf2_2="/usr/share/sounds/sf2/FluidR3_GS.sf2"
fi

notify_send=`notify-send -v 2>/dev/null`

if [ -z "$sf2_1" ] && [ -z "$sf2_2"]
then
  echo "$MES1"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES1"
  fi
  exit 1
fi

if [ -z "$sf2_1" ]
then
  echo "$MES3"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES3"
  fi
  exit 1
fi

if [ -z "$sf2_2"]
then
  echo "$MES4"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES4"
  fi
  exit 1
fi

fluidsynth -s -C 0 -R 0 -r 22050 -c 6 -z 128 -l -a alsa -o audio.alsa.device=plughw:0 -o midi.alsa_seq.id=fs $sf2_1 $sf2_2 &
PID=$!
sleep 1
process=`ps -p $PID -o comm=`
if [ -z $process ]
then
  echo "$MES2 $MES5"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES2 $MES5"
  fi
  exit 1
fi
pianobooster
kill $PID
