#!/bin/bash
#rename to makemusic.bat to run on windows

# create the output dir if does not exist
[ -a output ] || mkdir "output"

# from abc plus
abcm2ps -s 0.9 -c $1.abc -O output/$1.ps

# from imagemagick
convert -density 120x120 output/$1.ps output/$1.png

