#!/bin/bash
#rename to makemusic.bat to run on windows

# create the output dir if does not exist
[ -a PianoBoosterMusic ] || mkdir "PianoBoosterMusic"


# from abc plus
echo make music with $1
abc2midi $1.abc -o ${1}.solo.mid -RS

# from Musical MIDI Accompaniment
mma $1.mma -f PianoBoosterMusic/${1}.mid
