.\" (c) 2011 Miriam Ruiz <little_miry@yahoo.es>
.\" 
.\" This document is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" This package is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this package; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
.TH "PianoBooster" "6" "" "" ""
.SH "NAME"
pianobooster \- learn the piano just by playing a game
.SH "DESCRIPTION"
Piano Booster is piano teaching software that can provide piano lessons for beginners as well as for advanced players. It can be used for teaching music theory and is useful for piano practice and learning piano technique. 
.SH "SYNOPSIS"
.B pianobooster
[\fIflags\fR] [\fImidifile\fR]
.SH "OPTIONS"
.TP
\-d
Increase the debug level
.TP
\-q
Quick start
.TP
\-h, \-\-help
Display a help message
.TP
\-v
Display the version number and exit
.SH "USAGE"
Piano Booster is a fun way of playing along with a musical accompaniment and at the same time learning the basics of reading musical notation. The difference between playing along to a CD or a standard midi file is that Piano Booster listens and follows what you are playing on a midi piano keyboard. 

The program has been designed to allow you to play along on a midi piano keyboard with the scrolling notes shown on the screen. The notes you press on the keyboard appear as coloured lines on the musical stave, the colour of which depends whether you have pressed the right or wrong note.

A different musical instrument sound is used for your playing depending whether you are playing the right or wrong notes. This feature also allows Piano Booster to be used with printed sheet music so you can hear if you are playing the right notes while at the same time keeping your eyes on the printed score. The music accompaniment will automatically wait for you to find and play the correct notes in the piece.

Timing markers show whether you are playing ahead or behind of the beat. They appear as white crosses that are drawn over the note.
.SH "FEATURES"
- Piano Booster follows you when playing along to a musical accompaniment. If you stop, then so does the music.
.br
- Play a single hand and Piano Booster will play the other hand, as well as the rest of instruments, in time with you.
.br
- Change the speed of playback to match your playing ability.
.br
- Transpose +/- 12 semitones without stopping the play back.
.br
- Change the Key Signature of the piece.
.br
- Plays any standard midi or kar file.
.br
- Play along to any instrument in the midi file.
.br
- Adjust the volume of the current part or the volume your piano part.
.br
- See how accurate you're playing.
.br
- Change the start bar to start playing from any bar in the music. The repeat bars allows you to practice just a few difficult bars continuously.
.br
- Timing markers are white crosses that are drawn over each note and show if you are playing ahead or behind the beat.
.br
- A different instrument sound is used for the right and wrong notes that you play.
.SH "SEE ALSO"
You can find more about the game on its homepage: http://pianobooster.sourceforge.net/
.SH "AUTHOR"
The game has been written by Louis J. Barman <louisjb@users.sourceforge.net>. This manual page was written by Miriam Ruiz <little_miry@yahoo.es> for the Debian project.
