#!/bin/sh

# This script runs pinobooster with timidity
# It supports ALSA only
# TiMidity in Debian compilled without Libao mode -OO, using ALSA pcm device instead -Os
# License: same with Pianobooster
# Author: Alexey Loginov <alexl@mageia.org>

MES1="Error: timidity was not found or broken!"
MES2="Error: timidity does not have -OO or -Os options!"
MES3="Error: timidity does not have -iA option!"

lang=`echo $LANGUAGE|cut -d ":" -f 2`

if [ -z "$lang" ]
then
  lang=`echo $LANG|cut -d "_" -f 1`
fi

case $lang in
     ru|be)
          MES1="Ошибка: timidity не был найден, или он неработоспособен!"
          MES2="Ошибка: timidity не имеет опций -OO или -Os!"
          MES3="Ошибка: timidity не имеет опции -iA!"
          ;;
esac

notify_send=`notify-send -v 2>/dev/null`

timidity=`timidity -v 2>/dev/null`

if [ -z "$timidity" ]
then
  timidity=`timidity -h 2>/dev/null`
fi

if [ -z "$timidity" ]
then
   echo "$MES1"
   if [ ! -z "$notify_send" ]
   then
     notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES1"
   fi
   exit 1
fi

if [ ! -z "`timidity -help|grep '\-iA'`" ]
then
  if [ ! -z "`timidity -help|grep '\-OO'`" ]
  then
    timidity -iA -OO &
  else
    if [ ! -z "`timidity -help|grep '\-Os'`" ]
    then
      timidity -iA -Os &
    else
      echo "$MES2"
      if [ ! -z "$notify_send" ]
      then
        notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES2"
      fi
      exit 1
    fi
  fi
else
  echo "$MES3"
  if [ ! -z "$notify_send" ]
  then
    notify-send -a pianobooster -i pianobooster "PianoBooster" "$MES3"
  fi
  exit 1
fi

PID=$!

pianobooster

kill $PID
