#!/bin/sh

# This script runs pinobooster with timidity
# It supports ALSA only
# License: same with Pianobooster
# Author: Alexey Loginov <alexl@mageia.org>

timidity=`timidity -v 2>/dev/null`

if [ -z "$timidity" ]
then
   echo "Error: timidity was not found or broken!"
   exit 1
fi

if [ ! -z "`timidity -help|grep '\-OO'`" ]
then
  timidity -iA -OO &
else
  timidity -iA -Os &
fi

PID=$!

pianobooster

kill $PID
