name: Build

on: push

jobs:
  linux-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install dependencies
        run: sudo brew install cmake qt5 ftgl jack
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
          find .
