name: Build

on: push

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install dependencies
        run: sudo apt-get install build-essential cmake pkg-config libftgl-dev qtbase5-dev qttools5-dev librtmidi-dev fluid-soundfont-gm libfluidsynth-dev
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
          find .
  macos-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: fluidsynth dependencies
        run: |
          brew update || brew update
          brew upgrade
          brew install glib gobject-introspection libsndfile pkg-config jack dbus-glib pulseaudio portaudio sdl2
      - name: install fluidsynth
        run: |
          git clone git@github.com:FluidSynth/fluidsynth.git
          cd fluidsynth
          mkdir build && cd build
          cmake -Werror=dev -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1 -DNO_GUI=1 ..
          make
          sudo make install
      - name: Install dependencies
        run: brew install cmake qt5 ftgl jack fluidsynth pkg-config
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DWITH_INTERNAL_FLUIDSYNTH=OFF -DCMAKE_PREFIX_PATH=$(brew --prefix qt)
          make
          find .
