name: Build

on: push

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install dependencies
        run: apt-get install build-essential cmake pkg-config libftgl-dev qtbase5-dev qttools5-dev librtmidi-dev fluid-soundfont-gm libfluidsynth-dev
      - name: Build
        run: |
          mkdir build
          cmake .. -DWITH_INTERNAL_FLUIDSYNTH=ON
          make
          ls -la
